
name: github action test

on:
  push:
    branches:
      - master

jobs:
  myfirstJub:
    name: my first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME